
services:
  postgres:
    image: postgres:15
    container_name: hackathon_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - realtime_net
  
  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - realtime_net

volumes:
  postgres_data:

networks:
  realtime_net:
    driver: bridge